#ifndef HERMESFLATSCHEMA_READER_H
#define HERMESFLATSCHEMA_READER_H

/* Generated by flatcc 0.5.3-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif

typedef struct Hermes_Job_Ops Hermes_Job_Ops_t;
typedef const Hermes_Job_Ops_t *Hermes_Job_Ops_struct_t;
typedef Hermes_Job_Ops_t *Hermes_Job_Ops_mutable_struct_t;
typedef const Hermes_Job_Ops_t *Hermes_Job_Ops_vec_t;
typedef Hermes_Job_Ops_t *Hermes_Job_Ops_mutable_vec_t;

typedef const struct Hermes_Job_Ip4rng_table *Hermes_Job_Ip4rng_table_t;
typedef const flatbuffers_uoffset_t *Hermes_Job_Ip4rng_vec_t;
typedef flatbuffers_uoffset_t *Hermes_Job_Ip4rng_mutable_vec_t;
typedef const struct Hermes_Job_Prtrng_table *Hermes_Job_Prtrng_table_t;
typedef const flatbuffers_uoffset_t *Hermes_Job_Prtrng_vec_t;
typedef flatbuffers_uoffset_t *Hermes_Job_Prtrng_mutable_vec_t;
typedef const struct Hermes_Job_Targetlist_table *Hermes_Job_Targetlist_table_t;
typedef const flatbuffers_uoffset_t *Hermes_Job_Targetlist_vec_t;
typedef flatbuffers_uoffset_t *Hermes_Job_Targetlist_mutable_vec_t;
typedef const struct Hermes_Job_Portlist_table *Hermes_Job_Portlist_table_t;
typedef const flatbuffers_uoffset_t *Hermes_Job_Portlist_vec_t;
typedef flatbuffers_uoffset_t *Hermes_Job_Portlist_mutable_vec_t;
typedef const struct Hermes_Job_job_table *Hermes_Job_job_table_t;
typedef const flatbuffers_uoffset_t *Hermes_Job_job_vec_t;
typedef flatbuffers_uoffset_t *Hermes_Job_job_mutable_vec_t;
#ifndef Hermes_Job_Ip4rng_identifier
#define Hermes_Job_Ip4rng_identifier flatbuffers_identifier
#endif
#define Hermes_Job_Ip4rng_type_hash ((flatbuffers_thash_t)0x3a0a2424)
#define Hermes_Job_Ip4rng_type_identifier "\x24\x24\x0a\x3a"
#ifndef Hermes_Job_Prtrng_identifier
#define Hermes_Job_Prtrng_identifier flatbuffers_identifier
#endif
#define Hermes_Job_Prtrng_type_hash ((flatbuffers_thash_t)0x5de36a93)
#define Hermes_Job_Prtrng_type_identifier "\x93\x6a\xe3\x5d"
#ifndef Hermes_Job_Targetlist_identifier
#define Hermes_Job_Targetlist_identifier flatbuffers_identifier
#endif
#define Hermes_Job_Targetlist_type_hash ((flatbuffers_thash_t)0x469892f5)
#define Hermes_Job_Targetlist_type_identifier "\xf5\x92\x98\x46"
#ifndef Hermes_Job_Portlist_identifier
#define Hermes_Job_Portlist_identifier flatbuffers_identifier
#endif
#define Hermes_Job_Portlist_type_hash ((flatbuffers_thash_t)0xf4281ba3)
#define Hermes_Job_Portlist_type_identifier "\xa3\x1b\x28\xf4"
#ifndef Hermes_Job_Ops_identifier
#define Hermes_Job_Ops_identifier flatbuffers_identifier
#endif
#define Hermes_Job_Ops_type_hash ((flatbuffers_thash_t)0xa7ea19ec)
#define Hermes_Job_Ops_type_identifier "\xec\x19\xea\xa7"
#ifndef Hermes_Job_job_identifier
#define Hermes_Job_job_identifier flatbuffers_identifier
#endif
#define Hermes_Job_job_type_hash ((flatbuffers_thash_t)0xd455e93)
#define Hermes_Job_job_type_identifier "\x93\x5e\x45\x0d"


struct Hermes_Job_Ops {
    alignas(8) uint64_t bitops;
    alignas(4) uint32_t min_rtt_timeo;
    alignas(4) uint32_t init_rtt_timeo;
    alignas(4) uint32_t max_rtt_timeo;
    alignas(4) uint32_t host_timeo;
    alignas(4) uint32_t scan_delay;
    alignas(4) uint32_t max_scan_delay;
    alignas(4) uint32_t min_packet_rate;
    alignas(4) uint32_t max_packet_rate;
    alignas(4) uint32_t max_retries;
    alignas(4) uint32_t min_parallel;
    alignas(4) uint32_t max_parallel;
    alignas(4) uint32_t min_hostgroup;
    alignas(4) uint32_t max_hostgroup;
    alignas(4) uint32_t spoofed_srcaddr;
    alignas(2) uint16_t spoofed_srcport;
    alignas(2) uint16_t rpayload_len;
    alignas(1) uint8_t fragment_mtu;
    alignas(1) uint8_t ip_ttl;
    alignas(1) uint8_t thread_count;
    alignas(1) uint8_t verbose_level;
};
static_assert(sizeof(Hermes_Job_Ops_t) == 72, "struct size mismatch");

static inline const Hermes_Job_Ops_t *Hermes_Job_Ops__const_ptr_add(const Hermes_Job_Ops_t *p, size_t i) { return p + i; }
static inline Hermes_Job_Ops_t *Hermes_Job_Ops__ptr_add(Hermes_Job_Ops_t *p, size_t i) { return p + i; }
static inline Hermes_Job_Ops_struct_t Hermes_Job_Ops_vec_at(Hermes_Job_Ops_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t Hermes_Job_Ops__size() { return 72; }
static inline size_t Hermes_Job_Ops_vec_len(Hermes_Job_Ops_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(Hermes_Job_Ops)

__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, bitops, flatbuffers_uint64, uint64_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, min_rtt_timeo, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, init_rtt_timeo, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, max_rtt_timeo, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, host_timeo, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, scan_delay, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, max_scan_delay, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, min_packet_rate, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, max_packet_rate, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, max_retries, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, min_parallel, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, max_parallel, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, min_hostgroup, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, max_hostgroup, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, spoofed_srcaddr, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, spoofed_srcport, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, rpayload_len, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, fragment_mtu, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, ip_ttl, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, thread_count, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(Hermes_Job_Ops, verbose_level, flatbuffers_uint8, uint8_t)


struct Hermes_Job_Ip4rng_table { uint8_t unused__; };

static inline size_t Hermes_Job_Ip4rng_vec_len(Hermes_Job_Ip4rng_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Hermes_Job_Ip4rng_table_t Hermes_Job_Ip4rng_vec_at(Hermes_Job_Ip4rng_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Hermes_Job_Ip4rng_table_t, vec, i, 0)
__flatbuffers_table_as_root(Hermes_Job_Ip4rng)

__flatbuffers_define_scalar_field(0, Hermes_Job_Ip4rng, size, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, Hermes_Job_Ip4rng, start, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, Hermes_Job_Ip4rng, end, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct Hermes_Job_Prtrng_table { uint8_t unused__; };

static inline size_t Hermes_Job_Prtrng_vec_len(Hermes_Job_Prtrng_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Hermes_Job_Prtrng_table_t Hermes_Job_Prtrng_vec_at(Hermes_Job_Prtrng_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Hermes_Job_Prtrng_table_t, vec, i, 0)
__flatbuffers_table_as_root(Hermes_Job_Prtrng)

__flatbuffers_define_scalar_field(0, Hermes_Job_Prtrng, size, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(1, Hermes_Job_Prtrng, start, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(2, Hermes_Job_Prtrng, end, flatbuffers_uint16, uint16_t, UINT16_C(0))

struct Hermes_Job_Targetlist_table { uint8_t unused__; };

static inline size_t Hermes_Job_Targetlist_vec_len(Hermes_Job_Targetlist_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Hermes_Job_Targetlist_table_t Hermes_Job_Targetlist_vec_at(Hermes_Job_Targetlist_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Hermes_Job_Targetlist_table_t, vec, i, 0)
__flatbuffers_table_as_root(Hermes_Job_Targetlist)

__flatbuffers_define_scalar_field(0, Hermes_Job_Targetlist, total, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, Hermes_Job_Targetlist, ip_cnt, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, Hermes_Job_Targetlist, rng_cnt, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_vector_field(3, Hermes_Job_Targetlist, ip, flatbuffers_uint32_vec_t, 0)
__flatbuffers_define_vector_field(4, Hermes_Job_Targetlist, iprng, Hermes_Job_Ip4rng_vec_t, 0)

struct Hermes_Job_Portlist_table { uint8_t unused__; };

static inline size_t Hermes_Job_Portlist_vec_len(Hermes_Job_Portlist_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Hermes_Job_Portlist_table_t Hermes_Job_Portlist_vec_at(Hermes_Job_Portlist_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Hermes_Job_Portlist_table_t, vec, i, 0)
__flatbuffers_table_as_root(Hermes_Job_Portlist)

__flatbuffers_define_scalar_field(0, Hermes_Job_Portlist, total, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(1, Hermes_Job_Portlist, ip_cnt, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(2, Hermes_Job_Portlist, rng_cnt, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_vector_field(3, Hermes_Job_Portlist, port, flatbuffers_uint16_vec_t, 0)
__flatbuffers_define_vector_field(4, Hermes_Job_Portlist, prtrng, Hermes_Job_Prtrng_vec_t, 0)

struct Hermes_Job_job_table { uint8_t unused__; };

static inline size_t Hermes_Job_job_vec_len(Hermes_Job_job_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Hermes_Job_job_table_t Hermes_Job_job_vec_at(Hermes_Job_job_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Hermes_Job_job_table_t, vec, i, 0)
__flatbuffers_table_as_root(Hermes_Job_job)

__flatbuffers_define_struct_field(0, Hermes_Job_job, ops, Hermes_Job_Ops_struct_t, 0)
__flatbuffers_define_table_field(1, Hermes_Job_job, targets, Hermes_Job_Targetlist_table_t, 0)
__flatbuffers_define_table_field(2, Hermes_Job_job, ports, Hermes_Job_Portlist_table_t, 0)
__flatbuffers_define_table_field(3, Hermes_Job_job, syn_ports, Hermes_Job_Portlist_table_t, 0)
__flatbuffers_define_table_field(4, Hermes_Job_job, ack_ports, Hermes_Job_Portlist_table_t, 0)
__flatbuffers_define_table_field(5, Hermes_Job_job, udp_ports, Hermes_Job_Portlist_table_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* HERMESFLATSCHEMA_READER_H */
